site_name: ENOVIA Knowledge Base

# theme:
    # name: yeti
    # nav_style: dark

theme:
  name: material
  palette:
    primary: indigo
    scheme: slate
    accent: "deep orange"
  features:
    - content.tabs.link
    - navigation.tabs
    - toc.integrate
    - content.code.copy

# theme: windmill

plugins:
    - mkdocs-video 
    - tags
    - search:
        separator: '[\s\u200b\-]'
        lang: 
            - en
            - ja
        separator: '[\s\-\.]+'
        
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - attr_list
  - md_in_html

# plugins:
#   - glightbox


extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<song_hsu@126.com>
      name: Email to me 

  generator: false
  
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
repo_url: https://github.com/xuscode/enovia.git

copyright: Copyright &copy; 2023 DS USERS



    
